# 🚀 DEVELOPMENT ENVIRONMENT DOCKER COMPOSE
# Версия: 1.1.0-dev
# Изолированная среда разработки

version: '3.8'

services:
  frontend-dev:
    build: 
      context: ./frontend-dev
      dockerfile: Dockerfile
    container_name: chartgenius-frontend-dev
    ports:
      - "3001:3000"  # Отличный от продакшена порт
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8001
      - VITE_BOT_USERNAME=Chart_Genius_bot
      - VITE_VERSION=1.1.0-dev
      - VITE_ENVIRONMENT=development
    volumes:
      - ./frontend-dev/src:/app/src:ro  # Для hot reload
    networks:
      - dev-network
    restart: unless-stopped
    labels:
      - "traefik.enable=false"  # Отключаем traefik для dev
      - "environment=development"
      - "version=1.1.0-dev"

  backend-dev:
    build: 
      context: ./backend-dev
      dockerfile: Dockerfile
    container_name: chartgenius-backend-dev
    ports:
      - "8001:8000"  # Отличный от продакшена порт
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
      - VERSION=1.1.0-dev
      - CORS_ORIGINS=http://localhost:3001,http://127.0.0.1:3001
      - LOG_LEVEL=DEBUG
    env_file:
      - .env.development
    volumes:
      - ./backend-dev:/app:ro  # Для разработки
      - ./logs:/app/logs  # Логи
    networks:
      - dev-network
    restart: unless-stopped
    labels:
      - "environment=development"
      - "version=1.1.0-dev"

  bot-dev:
    build: 
      context: ./bot-dev
      dockerfile: Dockerfile
    container_name: chartgenius-bot-dev
    ports:
      - "8002:8000"  # Отличный от продакшена порт
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
      - VERSION=1.1.0-dev
      - BACKEND_URL=http://backend-dev:8000
    env_file:
      - .env.development
    volumes:
      - ./bot-dev:/app:ro  # Для разработки
      - ./logs:/app/logs  # Логи
    networks:
      - dev-network
    depends_on:
      - backend-dev
    restart: unless-stopped
    labels:
      - "environment=development"
      - "version=1.1.0-dev"

networks:
  dev-network:
    driver: bridge
    name: chartgenius-dev-network

volumes:
  dev-logs:
    name: chartgenius-dev-logs
