version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "${API_PORT:-8000}:8000"
    environment:
      - ENV_FILE=.env.docker
    volumes:
      - ./api/dev_logs:/app/api/dev_logs

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    depends_on:
      - api
    ports:
      - "${FRONTEND_PORT:-5173}:80"
    environment:
      - ENV_FILE=.env.docker
