# 🔍 ChartGenius Monitoring Stack
# Версия: 1.1.0-dev
# Grafana + Prometheus для технических метрик

version: '3.8'

services:
  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: chartgenius-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/rules:/etc/prometheus/rules
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=30d'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
    networks:
      - monitoring
    restart: unless-stopped
    labels:
      - "environment=development"
      - "service=monitoring"

  grafana:
    image: grafana/grafana:10.0.0
    container_name: chartgenius-grafana
    ports:
      - "3002:3000"  # Избегаем конфликта с frontend
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=chartgenius2025
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - monitoring
    restart: unless-stopped
    depends_on:
      - prometheus
    labels:
      - "environment=development"
      - "service=monitoring"

  redis:
    image: redis:7.0-alpine
    container_name: chartgenius-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    networks:
      - monitoring
    restart: unless-stopped
    labels:
      - "environment=development"
      - "service=cache"

  node-exporter:
    image: prom/node-exporter:v1.6.0
    container_name: chartgenius-node-exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - monitoring
    restart: unless-stopped

volumes:
  prometheus_data:
    name: chartgenius-prometheus-data
  grafana_data:
    name: chartgenius-grafana-data
  redis_data:
    name: chartgenius-redis-data

networks:
  monitoring:
    driver: bridge
    name: chartgenius-monitoring
